---
- hosts: all
  become: yes
  roles:
    - { role: geerlingguy.repo-epel, tags: ['all', 'epel'] }
    - { role: juwai.common,          tags: ['all', 'common'] }
    - { role: juwai.nginx,           tags: ['all', 'nginx'] }
    - { role: geerlingguy.php,       tags: ['all', 'php'] }
    - { role: geerlingguy.composer,  tags: ['all', 'composer'] }
    - { role: juwai.laravel,         tags: ['all', 'laravel'] }

  pre_tasks:
    - set_fact:
        ansible_distribution_major_version: '6'

- hosts: vagrant
  become: yes
  roles:
    - { role: juwai.memcached,       tags: ['all', 'memcached'] }

  tasks:
    - name: Install MySQL Community YUM Repo.
      yum: name=http://dev.mysql.com/get/mysql-community-release-el6-5.noarch.rpm state=installed
      tags: mysql

    - name: Install MySQL
      yum: name=mysql-community-server state=installed
      tags: mysql

    - name: Install MySQL-python
      yum: name=MySQL-python state=installed
      tags: mysql

    - name: Ensure MySQL is running
      service: name=mysqld state=started enabled=yes
      tags: mysql

    - name: Ensure IPTables is not running
      service: name=iptables state=stopped enabled=no
      tags: mysql

    - name: Update MySQL Root Password
      mysql_user: name=root host={{ item }} password={{ mysql_root_password }}
      with_items:
        - 127.0.0.1
        - ::1
        - localhost
      tags: mysql

    - name: Copy the my.cnf
      template: src=my.cnf dest=/root/.my.cnf owner=root mode=0600
      tags: mysql

    - name: Create database user
      mysql_user:
        login_user: 'root'
        login_password: '{{ mysql_root_password }}'
        name: 'xiong'
        password: 'password'
        host: '{{ item }}'
        priv: '*.*:ALL'
      with_items:
        - '%'
        - 'localhost'
      tags: 'mysql'

    - name: Create ec database
      mysql_db:
        login_user: 'root'
        login_password: '{{ mysql_root_password }}'
        name: 'ec'
        state: 'present'
        encoding: 'utf8'
        collation: 'utf8_general_ci'
      tags: mysql'

    - name: Run database migrations
      command: 'php artisan migrate'
      args:
        chdir: '/vagrant'
      register: migration_result
      changed_when: migration_result.stdout != 'Nothing to migrate.'
      ignore_errors: yes
      tags:
