---
- hosts: all
  become: yes
  roles:
    - { role: geerlingguy.repo-epel, tags: ['all', 'epel'] }
    - { role: juwai.common,          tags: ['all', 'common'] }
    - { role: juwai.nginx,           tags: ['all', 'nginx'] }
    - { role: geerlingguy.php,       tags: ['all', 'php'] }
    - { role: geerlingguy.composer,  tags: ['all', 'composer'] }
    - { role: juwai.laravel,         tags: ['all', 'laravel'] }

  pre_tasks:
    - set_fact:
        ansible_distribution_major_version: '6'

- hosts: vagrant
  become: yes
  roles:
    - { role: juwai.memcached,       tags: ['all', 'memcached'] }
